permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: yh80286
  email: yh80286@foxmail.com
  link: http://yh80286.github.com
  weibo: http://weibo.com/2692319004
  github: https://github.com/yh80286
 # music: http://site.douban.com/linanya
 # linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 岳豪的博客
description: My personal blog
url: http://yh80286.github.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/yh.jpg
favicon: /public/img/yh.jpg

# google analytics 设置
ga:
  id: UA-55958164-1 
  url: yh80286.github.io

# disqus 设置
disqus:
  shortname: yuehao

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
#  - 矩阵补全
#  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档